### ISSUE TITLE
programming PIC24

### ISSUE THREAD

**Issue by xb4rt** [AdamLaurie/mphidflash#25]
The issue is very similar to _Can't write hex to PIC24FJ64GB002_.
Function verifyBlockProgrammable seems to calculate the length of programmable block incorrectly (for pic24 family) since it uses 2 bytes per address. The memory block length reported by the bootloader is in the memory words. So I think function (verifyBlockProgrammable) should take information about bytesPerAddress into account.
`ML = devQuery.mem[ i ].Length * bytesPerAddress;`

**Comment by xb4rt** [comment]
This also applies to the main function. In the section where program prints out the configuration of reported memory blocks:
`(void)printf(": %d bytes free, addr: %04x, total %d\n",devQuery.mem[i].Length,devQuery.mem[i].Address,devQuery.memBlocks); `
It prints bytes number, even if, PIC24 bootloader reported words number.
Version I used is Release 1.8.

**Comment by AdamLaurie** [comment]
Do you have a fix/patch?

**Comment by xb4rt** [comment]
I've made a pull request.

**Comment by AdamLaurie** [comment]
thanks for the contribution!
